### ISSUE TITLE
Please fix this error 

### ISSUE THREAD

**Issue by Sahidmalik07** [cinemagoer/cinemagoer#417] opened 2022-11-23 02:59 UTC
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/find?q=sooryavanshi+-&s=tt', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 403: 'Forbidden'>}

**Comment by alberanid** [comment] 2022-11-27 11:29
closing as duplicate of #415

**Closed by alberanid** 2022-11-27 11:29 UTC
