### ISSUE TITLE
Person Filmography missing

### ISSUE THREAD

**Issue by DirkWuerdemann** [cinemagoer/cinemagoer#422] opened 2022-12-02 16:30 UTC
#### Issue description

The filmography of a person is not in the output anymore

#### Version of Cinemagoer = 2022-11-02, Python 3.7 and OS windows 11

**NOTICE: please always try the latest version from the repository before submitting a bug.**

- **Python:** `python3 -V` or, if you are using Python 2, `python -V`
- **Cinemagoer:** `python3 -c 'import imdb ; print(imdb.VERSION)'` or, if you are using Python 2, `python -c 'import imdb ; print(imdb.VERSION)'`
- **OS:** `python -c 'import platform ; print(platform.uname())'`

#### Steps to reproduce the issue

*if possible, provide a minimal code to reproduce the problem*

```python
#!/usr/bin/env python

# your code here
```

#### What's the expected result?

- 

#### What's the actual result?

- 

#### Additional details

-

**Comment by alberanid** [comment] 2022-12-03 12:42
closed as duplicate of #421

**Closed by alberanid** 2022-12-03 12:42 UTC
